### ISSUE TITLE
Add support for autoload

### ISSUE THREAD

**Issue by ermicioi** [HQarroum/timed-cache#24]
I would like to have an option to tell Cache to load some data in case it's missing when retrieving data with get() method.

`Cache.get(key, () => { return doLoading(); }`

The result of `doLoading()` should be saved to cache by key

**Comment by HQarroum** [comment]
Hi @ermicioi, sorry for the delay. I took your PR, modified it a bit and integrated it into the next release `1.1.3` which I just published. I closes your PR and let me know if I can close this issue. Thanks for your contribution !
